name: ehtim
channels:
  - conda-forge
  - eumetsat
  - intel
dependencies:
  - python=3.6
  - pynfft
  - jupyter
  - tqdm
  - requests
  - ipython
  - scikit-image
  - prompt_toolkit==2.0.10
  - setuptools==51.3.3
  - typing-extensions=3.7.4.3
  - pymc3
  - libopenblas
  - cython
  - contextvars
  - corner
  - openblas
  - colored
  - scikit-learn
  - astropy=4.0.2
